version: "3.8"

services:
  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5001:5001"
    networks:
      - ctm-network

  # Product Service
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "5002:5002"
    networks:
      - ctm-network

  # Order Service
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5003:5003"
    networks:
      - ctm-network

  # Content Service
  content-service:
    build: ./content-service
    container_name: content-service
    ports:
      - "5004:5004"
    networks:
      - ctm-network

  # Address Service
  address-service:
    build: ./address-service
    container_name: address-service
    ports:
      - "5005:5005"
    networks:
      - ctm-network

  # Recommender Service (Python)
  recommender-service:
    build: ./recommender-service
    container_name: recommender-service
    ports:
      - "5006:5006"
    networks:
      - ctm-network

networks:
  ctm-network:
    driver: bridge
